/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.app.frontend;

import com.mycompany.app.exceptions.InvalidGame;
import com.mycompany.app.models.UserAction;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.awt.GridLayout;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 *
 * @author Hazem
 */
public class GamePanel extends javax.swing.JPanel {

    private final MainFrame mainFrame;
    private final SudokuCell[][] cells = new SudokuCell[9][9];
    private final JPanel cellPanel = new JPanel(new GridLayout(9, 9, 2, 2));
    private int[][] board;

    /**
     * Creates new form GamePanel
     *
     * @param mainFrame
     */
    public GamePanel(MainFrame mainFrame) {
        initComponents();
        this.mainFrame = mainFrame;
        setMaximumSize(new Dimension(1920, 1080));
        setMinimumSize(mainFrame.getDimension());
        setPreferredSize(mainFrame.getDimension());
        initGridStructure();
        cellPanel.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        btnBack = new javax.swing.JButton();
        btnVerify = new javax.swing.JButton();
        btnUndo = new javax.swing.JButton();
        btnSolve = new javax.swing.JButton();
        labelTitle = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setLayout(new java.awt.GridBagLayout());

        btnBack.setBackground(new java.awt.Color(255, 153, 153));
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBack.setForeground(new java.awt.Color(0, 0, 0));
        btnBack.setText("Back");
        btnBack.setOpaque(true);
        btnBack.setPreferredSize(new java.awt.Dimension(90, 40));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 5);
        add(btnBack, gridBagConstraints);

        btnVerify.setBackground(new java.awt.Color(153, 255, 153));
        btnVerify.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnVerify.setForeground(new java.awt.Color(0, 0, 0));
        btnVerify.setText("Verify");
        btnVerify.setToolTipText("disabled unless the number of remaining empty cells is exactly 0");
        btnVerify.setOpaque(true);
        btnVerify.setPreferredSize(new java.awt.Dimension(90, 40));
        btnVerify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerifyActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 5);
        add(btnVerify, gridBagConstraints);

        btnUndo.setBackground(new java.awt.Color(255, 255, 153));
        btnUndo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUndo.setForeground(new java.awt.Color(0, 0, 0));
        btnUndo.setText("Undo");
        btnUndo.setOpaque(true);
        btnUndo.setPreferredSize(new java.awt.Dimension(90, 40));
        btnUndo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUndoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 212);
        add(btnUndo, gridBagConstraints);

        btnSolve.setBackground(new java.awt.Color(153, 153, 255));
        btnSolve.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSolve.setForeground(new java.awt.Color(0, 0, 0));
        btnSolve.setText("Solve");
        btnSolve.setToolTipText("disabled unless the number of remaining empty cells is exactly 5");
        btnSolve.setOpaque(true);
        btnSolve.setPreferredSize(new java.awt.Dimension(90, 40));
        btnSolve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSolveActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 106);
        add(btnSolve, gridBagConstraints);

        labelTitle.setFont(new java.awt.Font("Old English Text MT", 1, 48)); // NOI18N
        labelTitle.setForeground(new java.awt.Color(0, 0, 0));
        labelTitle.setText("Sudoku");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 10, 0);
        add(labelTitle, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        showHome();
        mainFrame.getCardLayout().show(mainFrame.getContentPane(), "home");
        mainFrame.getHomePanel().processCatalog();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnVerifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerifyActionPerformed
        if (countEmptyCells() > 0) {
            JOptionPane.showMessageDialog(this, "Please fill all cells before verifying.", "Incomplete", JOptionPane.WARNING_MESSAGE);
            return;
        }
        boolean[][] verification = this.mainFrame.getAdapter().verifyGame(board);
        boolean allValid = colorCells(verification);
        if (allValid) {
            boolean processed = mainFrame.getController().handleGameCompletion();
            if (processed) {
                    JOptionPane.showMessageDialog(this,
                            "Horaaaaaaay!! Congrats🎉\nGame Completed!",
                            "Valid Solution!",
                            JOptionPane.INFORMATION_MESSAGE);
                    showHome();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Some cells are incorrect (marked in red).", "Invalid Solution", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnVerifyActionPerformed

    private void btnUndoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUndoActionPerformed
        this.requestFocusInWindow();
        try {
            UserAction action = mainFrame.getAdapter().undoLastAction();
            if (action != null) {
                int r = action.getX();
                int c = action.getY();
                int prevVal = action.getPreviousValue();

                // Update internal board
                board[r][c] = prevVal;

                // Update GUI safely
                SwingUtilities.invokeLater(() -> {
                    String text = (prevVal == 0) ? "" : String.valueOf(prevVal);
                    cells[r][c].setText(text);
                });
            } else {
                JOptionPane.showMessageDialog(this, "Nothing to undo!", "Info", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error undoing action: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnUndoActionPerformed

    private void btnSolveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSolveActionPerformed
        if (countEmptyCells() != 5) {
            JOptionPane.showMessageDialog(this, "Solver only works when exactly 5 cells are empty.", "Solver Constraint", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            int[][] solutionSteps = mainFrame.getAdapter().solveGame(board);

            for (int[] step : solutionSteps) {
                int r = step[0];
                int c = step[1];
                int val = step[2];
                board[r][c] = val;
                cells[r][c].setText(String.valueOf(val));
                mainFrame.getAdapter().logAndUpdateCell(r, c, val);
            }
        } catch (InvalidGame ex) {
            JOptionPane.showMessageDialog(this, "Cannot solve this game state.", "Solver Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error solving game: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSolveActionPerformed

    private int countEmptyCells() {
        return mainFrame.getController().getEmptyCellCount();
    }

    private boolean colorCells(boolean[][] isValid) {
        boolean allValid = true;
        for (int row = 0; row < 9; row++) {
            // Fixed loop condition (was col < 0)
            for (int col = 0; col < 9; col++) {
                if (!isValid[row][col]) {
                    allValid = false;
                    cells[row][col].setBackground(new Color(255, 100, 100)); // Light Red
                }
            }
        }
        return allValid;
    }

    public void notifyCellChange(int row, int col, int value) {
        try {
            mainFrame.getAdapter().logAndUpdateCell(row, col, value);
        } catch (IOException ex) {
            System.err.println("Failed to log cell change: " + ex.getMessage());
        }
    }

    public void setupGame(int[][] newBoard) {
        this.board = newBoard;
        refreshGridUI();
        cellPanel.setVisible(true);
    }

    private void refreshGridUI() {
        for (int row = 0; row < 9; row++) {
            for (int col = 0; col < 9; col++) {
                int val = board[row][col];
                if (val == 0) {
                    cells[row][col].setBackground(new Color(232, 240, 254));
                    cells[row][col].setText("");
                    cells[row][col].setEditable(true);
                    
                } else {
                    cells[row][col].setBackground(Color.white);
                    cells[row][col].setText(String.valueOf(val));
                }
            }
        }
    }

    private void initGridStructure() {
        int cellPanelWidth = (int) ((mainFrame.getDimension().width) * 0.9);
        int cellPanelHeight = (int) ((mainFrame.getDimension().height) * 0.8);
        cellPanel.setPreferredSize(new Dimension(cellPanelWidth, cellPanelHeight));

        for (int row = 0; row < 9; row++) {
            for (int col = 0; col < 9; col++) {
                SudokuCell cell = new SudokuCell(row, col, this);
                cells[row][col] = cell;
                cellPanel.add(cell);
                cells[row][col].setBackground(Color.white);
            }
        }

        GridBagConstraints gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.CENTER;
        add(cellPanel, gbc);
    }

    private void showHome() {
        mainFrame.getCardLayout().show(mainFrame.getContentPane(), "home");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSolve;
    private javax.swing.JButton btnUndo;
    private javax.swing.JButton btnVerify;
    private javax.swing.JLabel labelTitle;
    // End of variables declaration//GEN-END:variables
}
