package com.mycompany.app.frontend;




import com.mycompany.app.controllers.SudokuController;
import com.mycompany.app.controllers.ViewAdapter;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Hazem
 */
public class MainFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());
    private final CardLayout cardLayout;
    private final HomePanel homePanel;
    private final GamePanel gamePanel;
    private final SudokuController controller;
    private final ViewAdapter adapter;
    private final Dimension dimension = new Dimension(1280,720);
    /**
     * Creates new form MainFrame
     * @param controller
     */
    public MainFrame(SudokuController controller) {
        this.controller = controller;
        this.adapter = new ViewAdapter(controller);
        initComponents();
        setTitle("Sudoku Game");
        setSize(1280,720);
        setMinimumSize(dimension);
        setMaximumSize(new Dimension(1920,1080));
        setPreferredSize(dimension);
        
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        cardLayout = new CardLayout();
        setLayout(cardLayout);
        setBackground(Color.white);
        
       homePanel = new HomePanel(this);
       add(homePanel,"home");
       
       gamePanel = new GamePanel(this);
       add(gamePanel,"game");
       
       cardLayout.show(getContentPane(), "home");
       setVisible(true);
       SwingUtilities.invokeLater(() -> {
            homePanel.processCatalog();
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public CardLayout getCardLayout()
    {
        return this.cardLayout;
    }
    
    public HomePanel getHomePanel()
    {
        return this.homePanel;
    }

    public GamePanel getGamePanel()
    {
        return this.gamePanel;
    }
    
    public Dimension getDimension()
    {
        return this.dimension;
    }

    public SudokuController getController() {
        return controller;
    }

    public ViewAdapter getAdapter() {
        return adapter;
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
