package com.mycompany.main;


import com.mycompany.app.controllers.SudokuController;
import com.mycompany.app.controllers.ViewAdapter;
import com.mycompany.app.controllers.services.GameObserver;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JFrame;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Hazem
 */
public class MainFrame extends javax.swing.JFrame /*implements GameObserver*/ {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());
    private final CardLayout cardLayout;
    private final HomePanel homePanel;
    private final GamePanel gamePanel;
    private final SudokuController controller = new SudokuController();
    private final ViewAdapter adapter = new ViewAdapter(controller);
    private final Dimension dimension = new Dimension(1280,720);
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        setTitle("Sudoku Game");
        setSize(1280,720);
        setMinimumSize(dimension);
        setMaximumSize(new Dimension(1920,1080));
        setPreferredSize(dimension);
        
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        cardLayout = new CardLayout();
        setLayout(cardLayout);
        setBackground(Color.white);
        
       homePanel = new HomePanel(this);
       add(homePanel,"home");
       
       gamePanel = new GamePanel(this);
       add(gamePanel,"game");
       
       cardLayout.show(getContentPane(), "game");
       setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }
    
    public CardLayout getCardLayout()
    {
        return this.cardLayout;
    }
    
    public HomePanel getHomePanel()
    {
        return this.homePanel;
    }

    public GamePanel getGamePanel()
    {
        return this.gamePanel;
    }
    
    public Dimension getDimension()
    {
        return this.dimension;
    }
    
//    @Override
//    /**
//     * Called when a single cell value changes (user input).
//     * @param row Row index (0-8)
//     * @param col Column index (0-8)
//     * @param newValue New value (0-9, where 0 means empty)
//     */
//    void onCellChanged(int row, int col, int newValue);
//    
//    @Override
//    /**
//     * Called when an undo operation is performed.
//     * @param row Row index of the cell being restored
//     * @param col Column index of the cell being restored
//     * @param restoredValue The value being restored
//     */
//    void onUndo(int row, int col, int restoredValue);
//    
//    @Override
//    /**
//     * Called when the game verification status changes.
//     * @param verificationResult String in format "STATE|row,col|row,col|..."
//     *                           where STATE is VALID, INVALID, or INCOMPLETE
//     *                           and row,col pairs indicate invalid cells (if any)
//     */
//    void onGameVerified(String verificationResult);
//    
//    @Override
//    /**
//     * Called when a new game is loaded.
//     * @param difficulty The difficulty level of the new game
//     */
//    void onNewGameLoaded(String difficulty);
//    
//    @Override
//    /**
//     * Called when a game is completed successfully (valid and no empty cells).
//     */
//    void onGameCompleted();
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
